SWP_back/src/main/java/controller/DoctorServlet.java

new commit

---

SWP_back/src/main/java/controller/PatientAppointmentServlet.java
SWP_back/src/main/java/dal/PatientAppointmentDAO.java

PatientAppointmentServlet, PatientAppointmentDAO update

---

SWP_back/src/main/java/controller/LoginServlet.java
SWP_back/src/main/java/dal/AccountPatientDAO.java
SWP_back/src/main/java/dal/AccountStaffDAO.java

loginservlet + patientdao staffdao

loginservlet + patientdao staffdao

---

SWP_back/src/main/java/controller/PatientAppointmentServlet.java
SWP_back/src/main/java/model/Account.java
SWP_back/src/main/java/model/AccountPatient.java
SWP_html/dashboard/assets/js/API/main-patient-encounters.js

update main-patient-encounters.js, PatientAppointmentServlet

update main-patient-encounters.js, PatientAppointmentServlet

---

SWP_html/frontend/assets/js/API/main-login.js

login_ver2_update_get_Id_patient

login_ver2

---

SWP_back/src/main/java/model/AccountPatient.java
SWP_html/dashboard/patient-appointment.html
SWP_html/dashboard/patient-encounters.html

update AccountPatient, /patient-appointment, /patient-encounters

update AccountPatient, /patient-appointment, /patient-encounters

---

SWP_html/dashboard/assets/js/API/main-patien-dashboard.js
SWP_html/dashboard/patient-dashboard.html
SWP_html/dashboard/patient-encounters.html

update patient-dashboard, patient-encounters, main-patien-dashboard

update patient-dashboard, patient-encounters, main-patien-dashboard

---

SWP_back/src/main/java/controller/AppointmentServlet.java
SWP_back/src/main/java/dal/AppointmentDAO.java

Udpate Add Appointment

---

SWP_back/src/main/java/controller/PatientAppointmentServlet.java
SWP_back/src/main/java/dal/PatientAppointmentDAO.java
SWP_back/src/main/java/dto/AppointmentPatientDTO.java
SWP_html/dashboard/assets/js/API/main-patient-payments.js
SWP_html/dashboard/patient-payments.html

change folder

---

SWP_back/src/main/java/controller/ReceptionistAppointmentServlet.java
SWP_back/src/main/java/dal/ReceptionistDAO.java
SWP_back/src/main/java/dto/ReceptionistCheckInDTO.java
SWP_html/dashboard/assets/js/API/main-receptionist-appointments.js
SWP_html/dashboard/receptionist-appointments.html
SWP_html/dashboard/receptionist-dashboard.html
SWP_html/frontend/assets/js/API/main-login.js

receptionist appointments (Check in appointment when patient visit)

receptionist appointments

---

SWP_back/src/main/java/controller/DoctorServlet.java
SWP_back/src/main/java/controller/PatientAppointmentServlet.java
SWP_back/src/main/java/controller/PatientPaymentServlet.java
SWP_back/src/main/java/controller/PatientServlet.java
SWP_back/src/main/java/dal/PatientAppointmentDAO.java
SWP_html/dashboard/assets/js/API/main-patien-dashboard.js
SWP_html/dashboard/assets/js/API/main-patient-doctors.js
SWP_html/dashboard/assets/js/API/main-patient-encounters.js
SWP_html/dashboard/assets/js/API/main-patient-patient.js
SWP_html/dashboard/assets/js/API/main-patient-payments.js
SWP_html/dashboard/assets/js/plugins/bookappointment.js
SWP_html/dashboard/patient-appointment.html

update Appoinment v2

---

SWP_back/src/main/java/controller/ReceptionistBookAppointmentServlet.java
SWP_back/src/main/java/dal/ReceptionistDAO.java
SWP_html/dashboard/assets/js/API/main-receptionist-appointments.js
SWP_html/dashboard/assets/js/API/main-receptionist-book-on-behalf.js
SWP_html/dashboard/receptionist-book-on-behalf.html

ReceptionistBookAppointmentServlet

ReceptionistBookAppointmentServlet

---

SWP_back/src/main/java/controller/AdminPatientServlet.java
SWP_back/src/main/java/controller/PatientServlet.java
SWP_back/src/main/java/dal/PatientDAO.java
SWP_html/dashboard/assets/js/API/main-adminbusiness-patient.js
SWP_html/dashboard/assets/js/API/main-patient-patient.js
SWP_html/dashboard/patient.html

admin business patient

---

SWP_back/src/main/java/dal/ReceptionistDAO.java
SWP_html/dashboard/assets/js/API/main-receptionist-update-infor.js
SWP_html/dashboard/receptionist-appointments.html
SWP_html/dashboard/receptionist-book-on-behalf.html
SWP_html/dashboard/receptionist-dashboard.html
SWP_html/dashboard/receptionist-waitlists.html

update infor change password

---

SWP_back/src/main/java/controller/AdminBusinessServlet.java
SWP_back/src/main/java/dal/AdminBusinessDAO.java
SWP_back/src/main/java/model/ListOfMedicalService.java
SWP_html/dashboard/assets/js/API/main-adminbusiness-list-medical-service.js
SWP_html/dashboard/products.html

List of service of admin business

List of service of admin business

---

SWP_back/src/main/java/controller/MedicineServlet.java
SWP_back/src/main/java/dal/MedicineDAO.java
SWP_html/dashboard/AccountManager_Admin.html
SWP_html/dashboard/assets/css/body-layout-improvements.css
SWP_html/dashboard/assets/css/table-center-fullscreen.css
SWP_html/dashboard/assets/css/table-full-width.css
SWP_html/dashboard/assets/css/table-responsive-improvements.css
SWP_html/dashboard/assets/js/API/main-phamarcist-dashboard.js
SWP_html/dashboard/assets/js/API/main-prescriptionDetail.js
SWP_html/dashboard/assets/js/table-center-enhancements.js
SWP_html/dashboard/assets/js/table-enhancements.js
SWP_html/dashboard/layout-demo.html
SWP_html/dashboard/medicineList.html
SWP_html/dashboard/patient-medical-profile.html
SWP_html/dashboard/pharmacist-dashboard.html
SWP_html/dashboard/prescriptionDetails.html
SWP_html/dashboard/prescriptionList.html
SWP_html/dashboard/table/README.md
SWP_html/dashboard/table/TABLE_CENTER_GUIDE.md
SWP_html/dashboard/table/bootstrap-table.html
SWP_html/dashboard/table/border-table.html
SWP_html/dashboard/table/demo-table-center.html
SWP_html/dashboard/table/fancy-table.html
SWP_html/dashboard/table/fixed-table.html
SWP_html/dashboard/table/table-data.html

Update Phamarcist Dashborad, Update Medicine Manager, Update Prescription Manager

Update Phamarcist Dashborad, Update Medicine Manager

---

SWP_back/src/main/java/controller/AdminBusinessServlet.java
SWP_back/src/main/java/dal/AdminBusinessDAO.java
SWP_html/dashboard/assets/js/API/main-adminbusiness-list-medical-service.js
SWP_html/dashboard/products.html

filter by status in list service

filter by status in list service

---

SWP_html/dashboard/addDoctor-Schedule.html

Udpate addDoctor-Schedule, Create adminSystem_Dashboard

Udpate addDoctor-Schedule, Create adminSystem_Dashboard

---

SWP_html/dashboard/adminbusiness-appointment-report.html

update report Appointment

---

SWP_html/dashboard/adminbusiness-appointment-report.html
SWP_html/dashboard/adminbusiness-feedback-report.html
SWP_html/dashboard/adminbusiness-onlinePay-report.html
SWP_html/dashboard/adminbusiness-patientRecord.html
SWP_html/dashboard/appointment.html
SWP_html/dashboard/assets/js/API/main-adminbusiness-appointment-report.js
SWP_html/dashboard/category.html
SWP_html/dashboard/doctors.html
SWP_html/dashboard/index.html
SWP_html/dashboard/patient.html
SWP_html/dashboard/receptionist.html
SWP_html/dashboard/report.html

update fe admin business

---

SWP_html/dashboard/DoctorScheduleList.html
SWP_html/dashboard/addDoctor-Schedule.html

Update Add Doctor Schedule

---

SWP_html/dashboard/assets/js/API/main-medicines.js
SWP_html/dashboard/assets/js/API/main-phamarcist-dashboard.js
SWP_html/dashboard/assets/js/API/main-pharmacist-prescriptionList.js
SWP_html/dashboard/medicineList.html
SWP_html/dashboard/pharmacist-dashboard.html
SWP_html/dashboard/prescriptionList.html

Udpate medicine Manager, Udpate Prescription Manager

Udpate medicine Manager, Udpate Prescription Manager

---

SWP_back/src/main/java/controller/AdminBusinessPatientRecordServlet.java
SWP_back/src/main/java/dal/AdminBusinessReportDAO.java
SWP_html/dashboard/adminbusiness-patientRecord.html
SWP_html/dashboard/adminbusiness-view-recordPatient.html
SWP_html/dashboard/assets/js/API/main-adminbusiness-view-recordPatient.js

update AdminBusiness Patient Record

update AdminBusiness Patient Record

---

SWP_html/frontend/registration.html

update screen register

---

SWP_back/src/main/java/controller/AdminBusinessRevenueReportServlet.java
SWP_back/src/main/java/dal/AdminBusinessReportDAO.java
SWP_back/src/main/java/dto/InvoiceStatusDTO.java
SWP_back/src/main/java/dto/MonthlyRevenueDTO.java
SWP_back/src/main/java/dto/RevenueByDepartmentDTO.java
SWP_back/src/main/java/dto/RevenueByTypeDTO.java
SWP_back/src/main/java/dto/TopDoctorDTO.java
SWP_back/src/main/java/dto/TopServiceDTO.java
SWP_back/src/main/java/dto/TotalRevenueDTO.java
SWP_html/dashboard/adminbusiness-onlinePay-report.html
SWP_html/dashboard/assets/js/API/main-adminbusiness-report-invoice.js

AdminBusiness Revenue Report

---

SWP_back/src/main/java/dal/ReceptionistDAO.java
SWP_html/dashboard/assets/js/API/main-receptionist-dashboard.js
SWP_html/dashboard/assets/js/API/main-receptionist-update-infor.js
SWP_html/dashboard/receptionist-dashboard.html

hashpassword in change password receptionist

hashpassword in change password receptionist

---

SWP_back/src/main/java/controller/PatientChangePassInfoServlet.java
SWP_html/dashboard/assets/js/API/main-logout-img-edit.js
SWP_html/dashboard/assets/js/API/main-patient-doctors.js
SWP_html/dashboard/assets/js/API/main-patient-medical-profile.js
SWP_html/dashboard/assets/js/API/main-patient-payments.js
SWP_html/dashboard/assets/js/API/main-patient-record.js
SWP_html/dashboard/patient-appointment.html
SWP_html/dashboard/patient-dashboard.html
SWP_html/dashboard/patient-doctor-profile.html
SWP_html/dashboard/patient-doctors.html
SWP_html/dashboard/patient-encounters.html
SWP_html/dashboard/patient-medical-profile.html
SWP_html/dashboard/patient-patient.html
SWP_html/dashboard/patient-payments.html
SWP_html/dashboard/patient-record.html

update tiếng việt

---

SWP_html/dashboard/assets/js/API/main-receptionist-waitlists.js
SWP_html/dashboard/receptionist-waitlists.html

update screen waitlist

---

SWP_back/src/main/java/controller/AccountManagementServlet.java
SWP_html/dashboard/AccountManager_Admin.html
SWP_html/dashboard/prescriptionDetails.html
SWP_html/dashboard/prescriptionList.html

Update Admin_dashboard. Update phamarcist__dashboard

Update Admin_dashboard. Update phamarcist__dashboard

---

SWP_html/dashboard/add_newAccountpatient.html
SWP_html/dashboard/pharmacist_account_create.html
SWP_html/dashboard/staff_account_create.html

Update Validate Create Account

Update Validate Create Account

---

SWP_html/dashboard/adminbusiness-appointment-report.html
SWP_html/dashboard/adminbusiness-feedback-report.html
SWP_html/dashboard/adminbusiness-onlinePay-report.html
SWP_html/dashboard/adminbusiness-patientRecord.html
SWP_html/dashboard/appointment.html
SWP_html/dashboard/assets/js/API/main-adminbusiness-appointment-report.js
SWP_html/dashboard/assets/js/API/main-adminbusiness-feedback.js
SWP_html/dashboard/assets/js/API/main-adminbusiness-home.js
SWP_html/dashboard/assets/js/API/main-adminbusiness-list-medical-service.js
SWP_html/dashboard/assets/js/API/main-adminbusiness-patient.js
SWP_html/dashboard/assets/js/API/main-adminbusiness-receptionist.js
SWP_html/dashboard/assets/js/API/main-adminbusiness-report-invoice.js
SWP_html/dashboard/assets/js/API/main-adminbusiness-view-recordPatient.js
SWP_html/dashboard/category.html
SWP_html/dashboard/doctors.html
SWP_html/dashboard/index.html
SWP_html/dashboard/patient.html
SWP_html/dashboard/products.html
SWP_html/dashboard/receptionist.html
SWP_html/dashboard/report.html

update admin home
